Contract: TodoList


2023-11-18 22:43:00,509: [96569] m.main:INFO: Registered plugins: IntrospectionAPIPlugin, <class 'manticore.ethereum.plugins.SkipRevertBasicBlocks'>, <class 'manticore.ethereum.plugins.FilterFunctions'>
2023-11-18 22:43:00,509: [96569] m.main:INFO: Beginning analysis
2023-11-18 22:43:00,515: [96569] m.e.manticore:INFO: Starting symbolic create contract
2023-11-18 22:43:02,765: [96569] m.e.manticore:INFO: Starting symbolic transaction: 0
2023-11-18 22:43:17,270: [96569] m.e.manticore:INFO: Found a concrete globalsha3 b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' -> 73138091548938366139099779971772605061518111956507126412222883840269740007539
2023-11-18 22:43:23,761: [96569] m.e.manticore:INFO: Found a concrete globalsha3 b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01' -> 27376155845717860833342594873357525089589924219251518322086369159840883582034
2023-11-18 22:44:45,262: [96569] m.e.manticore:INFO: 1 alive states, 3 terminated states
2023-11-18 22:44:47,176: [96569] m.e.manticore:INFO: Starting symbolic transaction: 1
2023-11-18 22:46:21,860: [96569] m.e.manticore:INFO: 2 alive states, 4 terminated states
2023-11-18 22:46:22,879: [96569] m.e.manticore:INFO: Starting symbolic transaction: 2
2023-11-18 22:48:34,205: [96569] m.c.worker:ERROR: Exception in state 0: ManticoreError('Forking on unfeasible constraint set')
Traceback (most recent call last):
  File "/Users/justyna/python_environment3_7/lib/python3.7/site-packages/manticore/core/worker.py", line 137, in run
    current_state.execute()
  File "/Users/justyna/python_environment3_7/lib/python3.7/site-packages/manticore/ethereum/state.py", line 8, in execute
    return self._platform.execute()
  File "/Users/justyna/python_environment3_7/lib/python3.7/site-packages/manticore/platforms/evm.py", line 3106, in execute
    self.current_vm.execute()
  File "/Users/justyna/python_environment3_7/lib/python3.7/site-packages/manticore/platforms/evm.py", line 1322, in execute
    raise Concretize("Symbolic PC", expression=expression, setstate=setstate, policy="ALL")
manticore.core.state.Concretize

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/justyna/python_environment3_7/lib/python3.7/site-packages/manticore/core/worker.py", line 158, in run
    m._fork(current_state, exc.expression, exc.policy, exc.setstate, exc.values)
  File "/Users/justyna/python_environment3_7/lib/python3.7/site-packages/manticore/core/manticore.py", line 518, in _fork
    raise ManticoreError("Forking on unfeasible constraint set")
manticore.exceptions.ManticoreError: Forking on unfeasible constraint set
 
2023-11-18 22:50:48,910: [96569] m.e.manticore:INFO: 3 alive states, 6 terminated states
2023-11-18 22:50:51,485: [96829] m.c.manticore:INFO: Generated testcase No. 0 - STOP(4 txs)
2023-11-18 22:50:51,487: [96829] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2023-11-18 22:50:51,855: [96830] m.c.manticore:INFO: Generated testcase No. 1 - STOP(4 txs)
2023-11-18 22:50:51,858: [96830] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2023-11-18 22:50:52,137: [96828] m.c.manticore:INFO: Generated testcase No. 2 - STOP(4 txs)
2023-11-18 22:50:52,140: [96828] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2023-11-18 22:51:38,360: [96569] m.c.manticore:INFO: Results in /Users/justyna/mcore_83zsgk3e
2023-11-18 22:51:38,360: [96569] m.c.manticore:INFO: Total time: 315.3714249134064
